# Generated by Django 4.2.4 on 2023-08-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="about",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
