# Generated by Django 4.2.4 on 2023-08-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_useraccount_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("coach", models.CharField(blank=True, max_length=255, null=True)),
                ("group", models.CharField(blank=True, max_length=255, null=True)),
                ("complete", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
