# Generated by Django 4.2.4 on 2023-08-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_calendarevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
    ]
