# Generated by Django 4.2.4 on 2024-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_traininggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
