# Generated by Django 4.2.4 on 2023-11-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarevents", "0002_remove_calendarevent_complete_usereventstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Breathing", "Blue"),
                    ("Focus/Concentration", "Green"),
                    ("Stress Management", "Orange"),
                    ("Reflection", "Yellow"),
                    ("Imagery/Visualization", "Red"),
                    ("Goal Setting", "Purple"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
