# Generated by Django 4.2.4 on 2023-09-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_traininggroup"),
        ("calendarevents", "0002_alter_calendarevent_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.traininggroup",
            ),
        ),
    ]
